"""
SQLAlchemy ORM models for BTC Signal Pro.

Each table maps directly to a domain concept:
  - PriceCandle   → raw OHLCV data from Binance
  - TechnicalIndicator → computed TA values per candle
  - Signal        → generated buy/sell signals with confidence
  - NewsItem      → fetched and filtered news articles
  - Alert         → fired notifications (price, signal, news, liquidation)
"""

from datetime import datetime
from typing import Optional

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    func,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Shared declarative base for all models."""
    pass


class PriceCandle(Base):
    """
    One row per 1-minute OHLCV candle for BTCUSDT.

    open_time is the primary key – Binance guarantees uniqueness per symbol
    per interval, so we use it directly instead of a surrogate key.
    """

    __tablename__ = "price_candles"

    open_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), primary_key=True)
    open_price: Mapped[float] = mapped_column(Numeric(18, 8), nullable=False)
    high_price: Mapped[float] = mapped_column(Numeric(18, 8), nullable=False)
    low_price: Mapped[float] = mapped_column(Numeric(18, 8), nullable=False)
    close_price: Mapped[float] = mapped_column(Numeric(18, 8), nullable=False)
    volume: Mapped[float] = mapped_column(Numeric(24, 8), nullable=False)
    close_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    quote_asset_volume: Mapped[float] = mapped_column(Numeric(24, 8), nullable=False)
    number_of_trades: Mapped[int] = mapped_column(Integer, nullable=False)
    taker_buy_base_volume: Mapped[float] = mapped_column(Numeric(24, 8), nullable=False)
    taker_buy_quote_volume: Mapped[float] = mapped_column(Numeric(24, 8), nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    indicator: Mapped[Optional["TechnicalIndicator"]] = relationship(
        "TechnicalIndicator", back_populates="candle", uselist=False
    )

    def __repr__(self) -> str:
        return f"<PriceCandle {self.open_time} close={self.close_price}>"


class TechnicalIndicator(Base):
    """
    Computed technical analysis values associated with a specific candle.

    All values may be NULL for the initial warm-up period before enough
    candles exist to compute the indicator.
    """

    __tablename__ = "technical_indicators"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    candle_time: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        ForeignKey("price_candles.open_time", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )
    # RSI
    rsi_14: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # MACD
    macd_line: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_signal: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    macd_histogram: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # EMA
    ema_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_50: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    ema_200: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Bollinger Bands (20-period, 2 std-dev)
    bb_upper: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bb_middle: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bb_lower: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    bb_percent_b: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Volume
    volume_sma_20: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    volume_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)  # vol / sma

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    candle: Mapped["PriceCandle"] = relationship("PriceCandle", back_populates="indicator")

    def __repr__(self) -> str:
        return f"<TechnicalIndicator {self.candle_time} rsi={self.rsi_14:.2f}>"


class Signal(Base):
    """
    A trading signal generated by the signal engine.

    Signals are only persisted when confidence >= SIGNAL_CONFIDENCE_THRESHOLD.
    """

    __tablename__ = "signals"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    signal_type: Mapped[str] = mapped_column(
        String(20), nullable=False
    )  # STRONG_BUY | BUY | HOLD | SELL | STRONG_SELL
    confidence: Mapped[float] = mapped_column(Float, nullable=False)  # 0–100

    # Price levels
    entry_price: Mapped[float] = mapped_column(Numeric(18, 8), nullable=False)
    take_profit: Mapped[float] = mapped_column(Numeric(18, 8), nullable=True)
    stop_loss: Mapped[float] = mapped_column(Numeric(18, 8), nullable=True)
    risk_reward_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    # Indicators that contributed
    indicators_agreed: Mapped[int] = mapped_column(Integer, nullable=False)
    indicator_details: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON blob

    # Outcome tracking (filled in retrospectively)
    outcome: Mapped[Optional[str]] = mapped_column(String(10), nullable=True)  # WIN / LOSS / OPEN
    outcome_price: Mapped[Optional[float]] = mapped_column(Numeric(18, 8), nullable=True)
    outcome_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    pnl_percent: Mapped[Optional[float]] = mapped_column(Float, nullable=True)

    alerts: Mapped[list["Alert"]] = relationship("Alert", back_populates="signal")

    def __repr__(self) -> str:
        return f"<Signal {self.signal_type} conf={self.confidence:.1f}% @ {self.entry_price}>"


class NewsItem(Base):
    """
    A news article fetched from one of the verified sources.

    Fake-news filtered items are stored with is_filtered=True so we can
    audit the filter logic without losing data.
    """

    __tablename__ = "news_items"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    source: Mapped[str] = mapped_column(String(50), nullable=False)  # coindesk | reuters | etc.
    title: Mapped[str] = mapped_column(Text, nullable=False)
    url: Mapped[str] = mapped_column(Text, nullable=False, unique=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    fetched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now()
    )

    # Sentiment
    sentiment: Mapped[Optional[str]] = mapped_column(
        String(10), nullable=True
    )  # BULLISH | BEARISH | NEUTRAL
    sentiment_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)  # -1.0 to 1.0

    # Geopolitical flags
    is_geopolitical: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    geo_keywords: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # comma-separated

    # Fake-news filter
    is_filtered: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    cross_referenced: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    def __repr__(self) -> str:
        return f"<NewsItem {self.source} '{self.title[:40]}...'>"


class Alert(Base):
    """
    A notification fired to the user (push, browser sound, or log-only).

    alert_type values:
      PRICE_LEVEL   – price approaching key support/resistance
      NEW_SIGNAL    – a trading signal was generated
      BREAKING_NEWS – high-impact news detected
      LIQUIDATION   – liquidation cascade warning
    """

    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    alert_type: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    message: Mapped[str] = mapped_column(Text, nullable=False)
    triggered_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), index=True
    )
    is_sent: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    sent_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    send_error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    # Optional FK to the signal that triggered this alert
    signal_id: Mapped[Optional[int]] = mapped_column(
        BigInteger, ForeignKey("signals.id", ondelete="SET NULL"), nullable=True
    )
    signal: Mapped[Optional["Signal"]] = relationship("Signal", back_populates="alerts")

    def __repr__(self) -> str:
        return f"<Alert {self.alert_type} sent={self.is_sent}>"
