"""
Alert manager for BTC Signal Pro — Phase 4.

Handles four alert types:
  PRICE_LEVEL   – price approaching a key support/resistance level
  NEW_SIGNAL    – a trading signal was generated by the signal engine
  BREAKING_NEWS – high-impact or geopolitical news detected
  LIQUIDATION   – liquidation cascade exceeds threshold

Alert delivery:
  1. Firebase Cloud Messaging (push to mobile)
  2. WebSocket broadcast to connected browser clients
  3. Persisted to PostgreSQL alert history log

Firebase is optional: if credentials are not configured the alert is
still stored in the DB and broadcast over WebSocket.
"""

import json
import logging
from datetime import datetime, timezone
from enum import Enum
from typing import Optional

from config import settings

logger = logging.getLogger(__name__)


class AlertType(str, Enum):
    PRICE_LEVEL = "PRICE_LEVEL"
    NEW_SIGNAL = "NEW_SIGNAL"
    BREAKING_NEWS = "BREAKING_NEWS"
    LIQUIDATION = "LIQUIDATION"


class FirebaseNotifier:
    """
    Thin wrapper around Firebase Admin SDK for push notifications.

    Lazy-initialises the Firebase app on first use so the application
    starts cleanly even when Firebase credentials are not configured.
    """

    def __init__(self) -> None:
        self._initialised = False
        self._app = None

    def _ensure_init(self) -> bool:
        """Initialise Firebase app if credentials are available. Returns True on success."""
        if self._initialised:
            return self._app is not None

        self._initialised = True
        creds = settings.firebase_credentials

        if not creds.get("project_id"):
            logger.warning(
                "Firebase not configured (FIREBASE_PROJECT_ID is empty). "
                "Push notifications will be disabled."
            )
            return False

        try:
            import firebase_admin
            from firebase_admin import credentials as firebase_credentials

            cred = firebase_credentials.Certificate(creds)
            self._app = firebase_admin.initialize_app(cred)
            logger.info("Firebase Admin SDK initialised for project: %s", creds["project_id"])
            return True
        except Exception as exc:
            logger.error("Firebase initialisation failed: %s", exc)
            return False

    async def send(
        self,
        title: str,
        body: str,
        alert_type: AlertType,
        extra_data: Optional[dict] = None,
        topic: str = "btc_signals",
    ) -> bool:
        """
        Send a push notification to all subscribers of the given topic.

        Returns True if the message was accepted by Firebase, False otherwise.
        Does not raise — errors are logged and False is returned.
        """
        if not self._ensure_init():
            return False

        try:
            import firebase_admin.messaging as fcm

            message = fcm.Message(
                notification=fcm.Notification(title=title, body=body),
                data={
                    "alert_type": alert_type.value,
                    "timestamp": datetime.now(timezone.utc).isoformat(),
                    **(extra_data or {}),
                },
                topic=topic,
                android=fcm.AndroidConfig(priority="high"),
                apns=fcm.APNSConfig(
                    payload=fcm.APNSPayload(
                        aps=fcm.Aps(sound="default", badge=1)
                    )
                ),
            )
            response = fcm.send(message)
            logger.info("FCM message sent: %s", response)
            return True

        except Exception as exc:
            logger.error("FCM send failed: %s", exc)
            return False


class WebSocketBroadcaster:
    """
    Broadcasts alert payloads to all connected WebSocket clients.

    Connected clients register themselves via add_client(); they
    should call remove_client() when their connection closes.
    """

    def __init__(self) -> None:
        self._clients: set = set()

    def add_client(self, ws) -> None:
        self._clients.add(ws)
        logger.debug("WS client connected (%d total)", len(self._clients))

    def remove_client(self, ws) -> None:
        self._clients.discard(ws)
        logger.debug("WS client disconnected (%d remaining)", len(self._clients))

    async def broadcast(self, payload: dict) -> None:
        """Send a JSON payload to all connected WebSocket clients."""
        if not self._clients:
            return

        import asyncio

        message = json.dumps(payload)
        dead_clients = set()

        async def _send_to(ws):
            try:
                await ws.send_text(message)
            except Exception:
                dead_clients.add(ws)

        await asyncio.gather(*(_send_to(ws) for ws in list(self._clients)))

        # Clean up closed connections
        for ws in dead_clients:
            self.remove_client(ws)


class AlertManager:
    """
    Central alert dispatcher.

    Orchestrates Firebase push notifications, WebSocket broadcasts, and
    database persistence for every alert event.
    """

    def __init__(self, db_session_factory=None) -> None:
        self._firebase = FirebaseNotifier()
        self._ws_broadcaster = WebSocketBroadcaster()
        self._db_factory = db_session_factory  # async session factory

    @property
    def ws_broadcaster(self) -> WebSocketBroadcaster:
        return self._ws_broadcaster

    async def fire_price_level_alert(
        self, current_price: float, level: float, level_type: str = "support"
    ) -> None:
        """
        Alert when BTC price approaches a key support/resistance level (within 1%).
        """
        deviation_pct = abs(current_price - level) / level * 100
        if deviation_pct > 1.0:
            return  # not close enough

        msg = (
            f"BTC approaching {level_type} level ${level:,.0f} "
            f"(current: ${current_price:,.0f}, {deviation_pct:.2f}% away)"
        )
        await self._dispatch(
            alert_type=AlertType.PRICE_LEVEL,
            title=f"⚠️ BTC {level_type.title()} Level Alert",
            message=msg,
            extra_data={"level": str(level), "level_type": level_type},
        )

    async def fire_signal_alert(self, signal_result) -> Optional[int]:
        """
        Alert when a trading signal is generated by the signal engine.

        Returns the DB alert ID on success.
        """
        emoji = {
            "STRONG_BUY": "🚀",
            "BUY": "📈",
            "HOLD": "⏸️",
            "SELL": "📉",
            "STRONG_SELL": "💥",
        }.get(signal_result.signal_type.value, "📊")

        msg = (
            f"{signal_result.signal_type.value} signal — "
            f"confidence {signal_result.confidence:.1f}% | "
            f"entry ${signal_result.entry_price:,.2f}"
        )
        return await self._dispatch(
            alert_type=AlertType.NEW_SIGNAL,
            title=f"{emoji} BTC {signal_result.signal_type.value}",
            message=msg,
            extra_data={
                "signal_type": signal_result.signal_type.value,
                "confidence": str(signal_result.confidence),
                "entry_price": str(signal_result.entry_price),
                "take_profit": str(signal_result.take_profit or ""),
                "stop_loss": str(signal_result.stop_loss or ""),
            },
        )

    async def fire_news_alert(self, title: str, source: str, sentiment: str) -> None:
        """Alert when a high-impact or geopolitical news article is detected."""
        msg = f"[{source.upper()}] {title} ({sentiment})"
        await self._dispatch(
            alert_type=AlertType.BREAKING_NEWS,
            title="📰 Breaking Crypto News",
            message=msg,
            extra_data={"source": source, "sentiment": sentiment},
        )

    async def fire_liquidation_alert(
        self, total_usd: float, long_usd: float, short_usd: float
    ) -> None:
        """Alert when liquidations exceed the configured threshold."""
        threshold_m = settings.LIQUIDATION_ALERT_THRESHOLD_M
        if total_usd < threshold_m * 1_000_000:
            return

        total_m = total_usd / 1_000_000
        msg = (
            f"Liquidation cascade: ${total_m:.0f}M total "
            f"(longs: ${long_usd / 1_000_000:.0f}M, "
            f"shorts: ${short_usd / 1_000_000:.0f}M)"
        )
        await self._dispatch(
            alert_type=AlertType.LIQUIDATION,
            title="🔥 Liquidation Cascade Warning",
            message=msg,
            extra_data={
                "total_usd": str(total_usd),
                "long_usd": str(long_usd),
                "short_usd": str(short_usd),
            },
        )

    # ── Private helpers ───────────────────────────────────────────────────

    async def _dispatch(
        self,
        alert_type: AlertType,
        title: str,
        message: str,
        extra_data: Optional[dict] = None,
        signal_id: Optional[int] = None,
    ) -> Optional[int]:
        """
        Send the alert through all channels and persist it to the database.

        Returns the database primary key of the persisted Alert row.
        """
        payload = {
            "type": "alert",
            "alert_type": alert_type.value,
            "title": title,
            "message": message,
            "timestamp": datetime.now(timezone.utc).isoformat(),
            **(extra_data or {}),
        }

        # 1. WebSocket broadcast (non-blocking, failures are tolerated)
        try:
            await self._ws_broadcaster.broadcast(payload)
        except Exception as exc:
            logger.error("WebSocket broadcast error: %s", exc)

        # 2. Firebase push notification
        push_sent = await self._firebase.send(
            title=title, body=message, alert_type=alert_type, extra_data=extra_data
        )

        # 3. Persist to database
        alert_id = await self._persist_alert(
            alert_type=alert_type,
            message=message,
            is_sent=push_sent,
            signal_id=signal_id,
        )

        return alert_id

    async def _persist_alert(
        self,
        alert_type: AlertType,
        message: str,
        is_sent: bool,
        signal_id: Optional[int] = None,
    ) -> Optional[int]:
        """Write the alert to the database.  Returns the new row's ID."""
        if not self._db_factory:
            logger.debug("No DB factory configured — alert not persisted.")
            return None

        try:
            from database.models import Alert

            async with self._db_factory() as session:
                alert = Alert(
                    alert_type=alert_type.value,
                    message=message,
                    is_sent=is_sent,
                    sent_at=datetime.now(timezone.utc) if is_sent else None,
                    signal_id=signal_id,
                )
                session.add(alert)
                await session.flush()
                alert_id = alert.id
                await session.commit()
                return alert_id
        except Exception as exc:
            logger.error("Failed to persist alert: %s", exc)
            return None
